[build]
  command = "npm install"
  publish = "public"

[build.environment]
  NODE_VERSION = "20"
  # optional, prevents Playwright from trying to download its own browsers
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "1"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium", "playwright-core"]
